version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-todo"
s3_bucket = "sam-app-samsoft"
s3_prefix = "sam-todo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
